spring:
  application:
    name: Self
  datasource:
    url: jdbc:postgresql://localhost:5432/self
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: false
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
logging:
  config: classpath:logback-prod.xml
  level:
    web: info
