[versions]
jjwt = "0.11.5"
mockito-koltin = "5.2.1"
mockito = "5.17.0"
hypersistence = "3.10.3"

[libraries]
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
mockito-koltin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-koltin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
hypersistence-utils = { module = "io.hypersistence:hypersistence-utils-hibernate-63", version.ref = "hypersistence" }
